version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: e_warehouse_db
    environment:
      - POSTGRES_DB=           #Заполнить название ДБ
      - POSTGRES_USER=        #Заполнить логин
      - POSTGRES_PASSWORD=    #Заполнить пароль
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d POSTGRES_DB -U POSTGRES_USER"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5433:5432"
    networks:
      - my_network
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./db/:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e_warehouse_app
    ports:
      - "5010:5010"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
